/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Decoder {
  constructor()
  push(chunk: Buffer): Array<JsItem>
  pushString(chunk: string): Array<JsItem>
  finish(): void
  reset(): void
  get lastEventId(): string
  get retry(): number | null
}
export type JsDecoder = Decoder

export declare function encodeComment(comment: string): Buffer

export declare function encodeEvent(event: JsEncodeEvent): Buffer

export declare function encodeRetry(retry: number): Buffer

export interface JsEncodeEvent {
  event?: string
  data: string
  id?: string
  retry?: number
}

export interface JsItem {
  kind: string
  event?: string
  data?: string
  id?: string
  retry?: number
}
